version: '3'
services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    restart: always
  api:
    build: ./api
    ports:
      - '5050:5050'
    restart: always
    